name: 'Libretto Action'
description: 'Libretto Action Description'
inputs:
  exampleInput:
    description: 'An example input'
    required: true
    default: 'default-value'
runs:
  using: 'node12'
  main: 'index.js'